services:
  db:
    image: postgres:16
    container_name: hoop_db
    environment:
      POSTGRES_USER: hoop
      POSTGRES_PASSWORD: hoop
      POSTGRES_DB: hoop_db
    ports:
      - "5432:5432"
    volumes:
      - hoop_pgdata:/var/lib/postgresql/data

volumes:
  hoop_pgdata:
